#!/usr/bin/env python3
"""def_pins_to_magic.py <design.def> > pins.tcl

Emit magic commands that put a port label on every top-level pin of a
P&R DEF, for the black-box LVS extraction (run_lvs_bb.sh).

Why: the Innovus streamOut of this flow writes NO pin text into the GDS
(checked 2026-09-05: `grep -a cpu_req_valid Cache_*.gds` = 0), so the
magic-extracted top cell has an empty port list and netgen stops at
"Top level cell failed pin matching". The DEF PINS section has every pin's
layer, rectangle, placement and orientation, so we rebuild the labels from
it: one small box at the centre of each pin rectangle, `label <name> center
<magic-layer>`, `port make` (per label; `port makeall` did only one).

Only the PINS section is parsed (the DEF is ~400 MB; we stop at END PINS).
Orientation handling follows the DEF convention (N none, E 90 cw, S 180,
W 270; FN/FS/FE/FW mirror first). Layer names map DEF -> magic sky130A
(met1..met5 -> metal1..metal5, li1 -> locali).
"""
import re, sys

LAYER = {'li1': 'locali', 'met1': 'metal1', 'met2': 'metal2',
         'met3': 'metal3', 'met4': 'metal4', 'met5': 'metal5'}

def orient(x, y, o):
    # mirror (flip about y axis) for F* first, then rotate
    if o.startswith('F'):
        x = -x
        o = o[1:]
    if o == 'N': return x, y
    if o == 'E': return y, -x       # 90 clockwise
    if o == 'S': return -x, -y
    if o == 'W': return -y, x       # 270 clockwise
    raise ValueError('orientation ' + o)

def main(path):
    units = 1000.0
    pins = []
    in_pins = False
    cur = None
    with open(path, errors='replace') as f:
        for line in f:
            if not in_pins:
                m = re.match(r'\s*UNITS DISTANCE MICRONS (\d+)', line)
                if m: units = float(m.group(1)); continue
                if line.startswith('PINS'): in_pins = True
                continue
            if line.startswith('END PINS'): break
            s = line.strip()
            if s.startswith('- '):
                if cur: pins.append(cur)
                cur = {'name': s.split()[1], 'rects': []}
            elif cur is not None:
                m = re.search(r'\+ LAYER (\S+) \( (-?\d+) (-?\d+) \) \( (-?\d+) (-?\d+) \)', s)
                if m:
                    cur['rects'].append((m.group(1), *map(int, m.group(2, 3, 4, 5))))
                m = re.search(r'\+ (?:PLACED|FIXED|COVER) \( (-?\d+) (-?\d+) \) (\w+)', s)
                if m:
                    cur['place'] = (int(m.group(1)), int(m.group(2)), m.group(3))
        if cur: pins.append(cur)
    n = 0
    print('# generated by def_pins_to_magic.py from %s : %d pins' % (path, len(pins)))
    for p in pins:
        if 'place' not in p or not p['rects']:
            print('# SKIP %s (no placement or geometry)' % p['name'], file=sys.stderr)
            continue
        px, py, o = p['place']
        for (lay, x1, y1, x2, y2) in p['rects']:
            ml = LAYER.get(lay)
            if ml is None:
                print('# SKIP %s layer %s' % (p['name'], lay), file=sys.stderr); continue
            cx, cy = orient((x1 + x2) / 2.0, (y1 + y2) / 2.0, o)
            ax, ay = (px + cx) / units, (py + cy) / units
            # a 0.04 um box at the pin centre; label text is the DEF pin name
            # (bus bits keep their [i]; magic accepts them in labels).
            print('box %.3fum %.3fum %.3fum %.3fum' % (ax - 0.02, ay - 0.02, ax + 0.02, ay + 0.02))
            print('label {%s} center %s' % (p['name'], ml))   # braces: bus bits like a[3] are Tcl command substitution otherwise
            print('port make')   # per label: `port makeall` only converted the label under the current box (magic 8.3.509, tested 2026-09-05)
            n += 1
            break   # one label per pin is enough for extraction
    print('# %d labels emitted' % n)
    print('# %d labels emitted for %d pins' % (n, len(pins)), file=sys.stderr)

if __name__ == '__main__':
    main(sys.argv[1])
